//! The behaviour-preservation gate: the converged generator must issue the
//! statements `stress.rs` issues, in order, byte for byte.
//!
//! # Why this file is the whole convergence
//!
//! Every performance number this project has recorded for the mixed-workload
//! lane came out of `stress.rs`. If the converged harness draws a slightly
//! different operation sequence — one shape picked at a different weight, one
//! key drawn from a different rng position, one statement with a space moved —
//! then every one of those numbers becomes incomparable to every number
//! recorded next, and nothing about the output would look wrong. A benchmark
//! that quietly changed what it measures is worse than one that broke.
//!
//! # What the golden is, and how it was made
//!
//! `tests/golden/stress-op-sequence.txt` was generated by a temporary binary
//! that was a VERBATIM copy of the working tree's `src/bin/stress.rs` with its
//! `main` disabled and a dump appended — so the file is the untouched
//! generator's own output, not a transcription of it. Three datasets ×
//! seventeen profiles × three clients × forty-eight operations, plus the churn
//! anchor each churn profile issues before its loop: 7,362 statements.
//!
//! Each line is `dataset|profile|client|index|kind|shape|arg|statement`.
//!
//! # What it proves, and what it does not
//!
//! It proves the SEQUENCE and the TEXT. It does not prove the timing, the
//! connection handling, or the level scoping — which is deliberate, because
//! level scoping is a declared CHANGE (see `plan::LEVEL_STRIDE`) and the
//! golden is generated at level index 0, where the scoping is the identity.
//! A converged run at a later level writes different id VALUES on the `snb`
//! dataset, and that is recorded rather than hidden.

use std::collections::BTreeMap;

use engram_bench::catalogue::{Catalogue, Dialect, Status, has_unbound, render};
use engram_bench::workload::{
    ChurnPlan, ChurnSet, ClientOps, Dataset, LevelSpec, Op, PROFILES, Param, WriteKind, bind_churn,
    bind_churn_anchor,
};

const GOLDEN: &str = include_str!("golden/stress-op-sequence.txt");

/// The datasets and key spaces the golden was generated with.
const BEDS: [(&str, Dataset, u64); 3] = [
    ("synthetic", Dataset::Synthetic, 20_000),
    ("snb", Dataset::Snb, 10_000),
    ("snb-platform", Dataset::SnbPlatform, 10_000),
];

const SEED: u64 = 424_242;
const NONCE: u64 = 1;
const CLIENTS: usize = 3;
const OPS: usize = 48;

fn render_one(
    cat: &Catalogue,
    family: &str,
    kind: &str,
    name: &str,
    params: &BTreeMap<String, Param>,
) -> String {
    let pairs: Vec<(String, String)> = params
        .iter()
        .map(|(k, v)| (k.clone(), v.render()))
        .collect();
    let refs: Vec<(&str, &str)> = pairs
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    let entry = match kind {
        "read" => cat.read_shape(name, Dialect::Cypher),
        _ => cat.write_op(name, family, Dialect::Cypher),
    }
    .unwrap_or_else(|e| panic!("{kind} {name}: {e}"));
    assert!(
        matches!(entry.status, Status::Verified),
        "{kind} {name}: the Cypher text a recorded baseline depends on must be `verified`"
    );
    let out = render(&entry.text, &refs);
    assert!(
        !has_unbound(&out),
        "{kind} {name}: rendered statement still carries a placeholder: {out}"
    );
    out
}

#[test]
fn the_converged_generator_issues_the_statements_stress_issues() {
    let cat = Catalogue::load().expect("the compiled-in catalogue must parse");
    let mut want = GOLDEN.lines();
    let mut checked = 0usize;
    for (dsname, dataset, keys) in BEDS {
        let spec = LevelSpec {
            seed: SEED,
            dataset,
            keys,
            nonce: NONCE,
        };
        let family = dataset.family().name();
        for prof in PROFILES {
            for cid in 0..CLIENTS {
                let mut ops = ClientOps::new(spec, prof, cid);
                let mut churn = ChurnSet::default();
                // The per-worker anchor, issued once before the loop.
                if prof.write_kind == WriteKind::DeleteChurn {
                    let (op, params) = bind_churn_anchor(cid, NONCE);
                    let got = render_one(&cat, family, "write", op, &params);
                    let line = want.next().expect("the golden ran out");
                    assert_line(line, dsname, prof.name, cid, "anchor", "write", "-", &got);
                    checked += 1;
                }
                for i in 0..OPS {
                    let (kind, shape, stmt) = match ops.next_op() {
                        Op::Read { shape, params } => (
                            "read",
                            shape.to_string(),
                            render_one(&cat, family, "read", shape, &params),
                        ),
                        Op::Write { op, params } => (
                            "write",
                            "-".to_string(),
                            render_one(&cat, family, "write", op, &params),
                        ),
                        Op::ChurnStep { seq } => {
                            // The golden was taken with every op acked, which
                            // is `stress.rs`'s churn under a server that
                            // refuses nothing — see `plan::client_stream`.
                            let plan = churn.plan(seq);
                            churn.ack(plan);
                            let (op, mut params) = bind_churn(plan, cid, NONCE);
                            if matches!(plan, ChurnPlan::Create { .. }) {
                                params.insert(
                                    "anchor".to_string(),
                                    Param::Uint((NONCE << 8) | cid as u64),
                                );
                            }
                            (
                                "write",
                                "-".to_string(),
                                render_one(&cat, family, "write", op, &params),
                            )
                        }
                    };
                    let line = want.next().expect("the golden ran out");
                    assert_line(
                        line,
                        dsname,
                        prof.name,
                        cid,
                        &i.to_string(),
                        kind,
                        &shape,
                        &stmt,
                    );
                    checked += 1;
                }
            }
        }
    }
    assert_eq!(
        want.next(),
        None,
        "the golden holds statements nothing replayed"
    );
    // A loop that checked nothing passes every assertion it never made.
    let churn_profiles = PROFILES
        .iter()
        .filter(|p| p.write_kind == WriteKind::DeleteChurn)
        .count();
    let expected = BEDS.len() * CLIENTS * (PROFILES.len() * OPS + churn_profiles);
    assert_eq!(
        checked, expected,
        "every golden line must have been compared"
    );
    assert_eq!(checked, 7_362);
}

#[allow(clippy::too_many_arguments)]
fn assert_line(
    line: &str,
    dsname: &str,
    profile: &str,
    cid: usize,
    index: &str,
    kind: &str,
    shape: &str,
    stmt: &str,
) {
    let f: Vec<&str> = line.splitn(8, '|').collect();
    assert_eq!(f.len(), 8, "malformed golden line: {line:?}");
    assert_eq!(
        (f[0], f[1], f[2], f[3], f[4], f[5]),
        (
            dsname,
            profile,
            format!("c{cid}").as_str(),
            index,
            kind,
            shape
        ),
        "the converged generator drew a different operation here"
    );
    assert_eq!(
        f[7], stmt,
        "\n{dsname}/{profile}/c{cid}/{index}: the statement text diverged\n  stress.rs: {}\n  converged: {stmt}",
        f[7]
    );
}
